version: '3.7'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 15672:15672
      - 5672:5672
